### ISSUE TITLE
IllinoisNet tool launcher connection problems

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#100]
Tools launched to the tool server on 141.142.210.18 can't be accessed on IllinoisNet. This was addressed once before but I don't recall specifics - believe there is a port conflict or something along those lines. Works on NCSAnet.

**Comment by robkooper** [comment]
This is due to docker and illinoisnet having the same IP address. I changed the ip address that docker uses in the hope it will solve this. Unfortunately I ended up restarting all tools.

Following is what was needed for the container to work:

```
mkdir /etc/systemd/system/docker.service.d
cat > /etc/systemd/system/docker.service.d/10-docker-bridge.conf << EOF
[Service]
Environment="DOCKER_OPT_BIP=--bip=192.168.200.1/24"
EOF

sudo systemctl daemon-reload
sudo systemctl restart docker.service
```

or if launching it with cloud-config

```
#cloud-config

coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 10-docker-bridge.conf
          content: |
            [Service]
            Environment="DOCKER_OPT_BIP=--bip=192.168.200.1/24"
```

If the issues persists please reopen this ticket
