### ISSUE TITLE
Marking error datasets and warnings/caveats

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#575]
Have an ERROR.txt or something in the dataset & on disk to indicate dataset should be skipped for processing.

**Comment by dlebauer** [comment]
See https://github.com/terraref/reference-data/issues/218

For data that a human has recognized as being in error (e.g. w/ blurry FLIR data, point clouds clipped at some height)  
1. add a text file named "ERROR" with optional content / explanation / pointer to a github issue, could be a set of key: value pairs, perhaps in yaml that get parsed directly to json metadata 
2. have an extractor that finds these files and adds a tag "quality"{ "ERROR" = "TRUE", "description":"", "key2":"value2"
3. add a a general rule perhaps at the level of extractors, or perhaps at the level of RabbitMQ that says any time an error (file or flag) is found, skip processing the dataset.

**Comment by dlebauer** [comment]
For example, for all FLIR data in 2017
```yml
quality:
  status: ERROR
  description: Sand and water contaminated FLIR Camera lens so temperature values are invalid  
  url: https://github.com/terraref/reference-data/issues/182
```


```
